In [1]:
import pandas as pd

df=pd.read_csv('../Data/payments_data_prepared.csv')
print(df.shape)
df.head()

(7043, 9)

,customerID,transaction_amount,customer_tenure_months,payment_method,retry_count,failure_reason,gateway_response_time_ms,customer_segment,payment_recovered
0,7590-VHVEG,358.2,1,Electronic check,0,insufficient_funds,272,new_customer,Yes
1,5575-GNVDE,683.4,34,Mailed check,3,bank_decline,544,high_value_repeat,Yes
2,3668-QPYBK,646.2,2,Mailed check,1,insufficient_funds,404,new_customer,No
3,7795-CFOCW,507.6,45,Bank transfer (automatic),1,network_error,2193,high_value_repeat,Yes
4,9237-HQITU,848.4,2,Electronic check,0,insufficient_funds,382,new_customer,No

In [2]:
threshold=df['transaction_amount'].median()
print(threshold)

844.1999999999999

In [3]:
df['is_high_value_transaction']=(df['transaction_amount']>threshold).astype(int)
df['is_high_value_transaction'].value_counts()

is_high_value_transaction
0    3528
1    3515
Name: count, dtype: int64

In [4]:
df['is_repeat_failure']=(df['retry_count']>1).astype(int)
df['is_repeat_failure'].value_counts()

is_repeat_failure
0    5294
1    1749
Name: count, dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerID                 7043 non-null   object
 1   transaction_amount         7043 non-null   float64
 2   customer_tenure_months     7043 non-null   int64
 3   payment_method             7043 non-null   object
 4   retry_count                7043 non-null   int64
 5   failure_reason             7043 non-null   object
 6   gateway_response_time_ms   7043 non-null   int64
 7   customer_segment           7043 non-null   object
 8   payment_recovered          7043 non-null   object
 9   is_high_value_transaction  7043 non-null   int64
 10  is_repeat_failure          7043 non-null   int64
dtypes: float64(1), int64(5), object(5)
memory usage: 605.4+ KB

In [6]:
df_encoded=pd.get_dummies(df,columns=['failure_reason','payment_method','customer_segment'])
print(df_encoded.columns.tolist())

['customerID', 'transaction_amount', 'customer_tenure_months', 'retry_count', 'gateway_response_time_ms', 'payment_recovered', 'is_high_value_transaction', 'is_repeat_failure', 'failure_reason_bank_decline', 'failure_reason_card_expired', 'failure_reason_insufficient_funds', 'failure_reason_network_error', 'payment_method_Bank transfer (automatic)', 'payment_method_Credit card (automatic)', 'payment_method_Electronic check', 'payment_method_Mailed check', 'customer_segment_high_value_repeat', 'customer_segment_new_customer', 'customer_segment_occasional']

In [7]:
df_encoded['payment_recovered']=df_encoded['payment_recovered'].map({'Yes':1,'No':0})
df_encoded['payment_recovered'].value_counts()

payment_recovered
0    3554
1    3489
Name: count, dtype: int64

In [8]:
df_encoded.columns
df_encoded.head()

,customerID,transaction_amount,customer_tenure_months,retry_count,gateway_response_time_ms,payment_recovered,is_high_value_transaction,is_repeat_failure,failure_reason_bank_decline,failure_reason_card_expired,failure_reason_insufficient_funds,failure_reason_network_error,payment_method_Bank transfer (automatic),payment_method_Credit card (automatic),payment_method_Electronic check,payment_method_Mailed check,customer_segment_high_value_repeat,customer_segment_new_customer,customer_segment_occasional
0,7590-VHVEG,358.2,1,0,272,1,0,0,False,False,True,False,False,False,True,False,False,True,False
1,5575-GNVDE,683.4,34,3,544,1,0,1,True,False,False,False,False,False,False,True,True,False,False
2,3668-QPYBK,646.2,2,1,404,0,0,0,False,False,True,False,False,False,False,True,False,True,False
3,7795-CFOCW,507.6,45,1,2193,1,0,0,False,False,False,True,True,False,False,False,True,False,False
4,9237-HQITU,848.4,2,0,382,0,1,0,False,False,True,False,False,False,True,False,False,True,False

In [9]:
y = df_encoded['payment_recovered']
X = df_encoded.drop(columns=['payment_recovered', 'customerID'])
print(X.shape)

(7043, 17)

In [10]:
X.columns

Index(['transaction_amount', 'customer_tenure_months', 'retry_count',
       'gateway_response_time_ms', 'is_high_value_transaction',
       'is_repeat_failure', 'failure_reason_bank_decline',
       'failure_reason_card_expired', 'failure_reason_insufficient_funds',
       'failure_reason_network_error',
       'payment_method_Bank transfer (automatic)',
       'payment_method_Credit card (automatic)',
       'payment_method_Electronic check', 'payment_method_Mailed check',
       'customer_segment_high_value_repeat', 'customer_segment_new_customer',
       'customer_segment_occasional'],
      dtype='object')

In [11]:
X.shape

(7043, 17)

In [12]:
y.shape

(7043,)

In [13]:
X.to_csv('../Data/X_features.csv',index=False)
y.to_csv('../Data/y_target.csv',index=False)

In [14]:
print(X.shape)
print(X.columns.tolist())

(7043, 17)
['transaction_amount', 'customer_tenure_months', 'retry_count', 'gateway_response_time_ms', 'is_high_value_transaction', 'is_repeat_failure', 'failure_reason_bank_decline', 'failure_reason_card_expired', 'failure_reason_insufficient_funds', 'failure_reason_network_error', 'payment_method_Bank transfer (automatic)', 'payment_method_Credit card (automatic)', 'payment_method_Electronic check', 'payment_method_Mailed check', 'customer_segment_high_value_repeat', 'customer_segment_new_customer', 'customer_segment_occasional']